cpus: 2
ram: 8192
disk1_size: 50
folder: "{{ infra_folder }}"                            # Where the VM template is stored
template: "{{ infra_template }}"			# Name of the template
ova_path: "{{ infra_ova_path }}"			# Name of the OVA used to import the template

#
# without cloud-init
#
#customvalues: []
#networks:
#  - name: '{{ vm_portgroup }}'
#    ip:  "{{ ansible_host }}"
#    netmask: "{{ dhcp_subnet | ipaddr('netmask') }}"
#    gateway: "{{ gateway }}"
#customization:
#  dns_servers:
#    "{{ internal_dns_servers | union(dns_servers) }}"
#  domain: "{{ cluster_name }}.{{ domain_name }}"
#disks_specs:
#  - size_gb:  '{{ disk1_size }}'
#    type: thin
#    datastore: "{{ datastores | random }}"

#
# with cloud init
#
customvalues: 
  - key: guestinfo.metadata
    value: "{{ cloud_init_metadata_data }}"
  - key: guestinfo.metadata.encoding
    value: base64
  - key: guestinfo.userdata
    value:  "{{ cloud_init_users_data }}"
  - key: guestinfo.userdata.encoding
    value: base64
networks:
  - name: '{{ vm_portgroup }}'
customization: {}
disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"

