###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
#######################################################################
#
# Play: Prepare ignition data files by running the OCP installer
#
#######################################################################
- name: Prepare Ignition data files
  hosts: localhost
  gather_facts: yes 

  roles:
  - role: ignition
    vars:
      provision: yes

#######################################################################
#
# Play: Provision OCP nodes
#
#######################################################################
- name: Provision Openshift nodes
  hosts: ocp
  gather_facts: false

  roles:
  - role: ocp
    vars:
      provision: yes

#######################################################################
#
# Play: Provision Load Balancers
#
#######################################################################
- name: Provision Load Balancers
  hosts: loadbalancer
  gather_facts: false

  roles:
  - role: loadbalancer
    vars:
      provision: yes

#######################################################################
#
# Play: Provision Infrastructure nodes
#
#######################################################################
- name: Provision Infrastructure nodes
  hosts: infrastructure
  gather_facts: false

  roles:
  - role: infrastructure
    vars:
      provision: yes

